# Site settings
title: Sustainable Summer
description: > # this means to ignore newlines until "baseurl:"
  Harlem Grown is on a mission to inspire youth to live HEALTHY and AMBITIOUS lives through mentorship and hands-on education in urban farming, sustainability and nutrition. We started a summer camp for youth to farm, learn, and have fun!
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://harlemgrown.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
